### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by lingo** [vprimachenko/Sublime-Colorcoder#51]
Here's the traceback.  It seems to be stuck in a loop for some reason.
I hope this report helps somehow... I've not seen this bug before, but today I can't avoid it.

```
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin JSHint Gutter.JSHint
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin User.ArgumentManipulation
plugins loaded
SublimeLinter: debug mode: off 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-07-17 10:55:21, next run at 2015-07-17 11:55:21 or after
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Clojure", "ActionScript", "Refactor", "TrailingSpaces", "ASP", "D", "C#", "AppleScript"]
reloading plugin Colorcoder.colorcoder
error: Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
[Errno 36] File name too long: '/home/user/.config/sublime-text-3/Packages/Colorcoder/Monokai (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (SL) (Colorcoded).tmTheme'
reloading Packages/Colorcoder/colorcoder.sublime-settings
generating syntax summary
reloading Packages/User/Preferences.sublime-settings
error: Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
[Errno 36] File name too long: '/home/user/.config/sublime-text-3/Packages/Colorcoder/Monokai (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (SL) (Colorcoded).tmTheme'
reloading Packages/User/Preferences.sublime-settings
error: Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
[Errno 36] File name too long: '/home/user/.config/sublime-text-3/Packages/Colorcoder/Monokai (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (SL) (Colorcoded).tmTheme'
ignored packages updated to: ["Clojure", "ActionScript", "Refactor", "TrailingSpaces", "ASP", "D", "C#", "AppleScript", "Colorcoder"]
unloading plugin Colorcoder.colorcoder
reloading Packages/Colorcoder/colorcoder.sublime-settings
generating syntax summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: The package Colorcoder has been removed
reloading Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Clojure", "ActionScript", "Refactor", "TrailingSpaces", "ASP", "D", "C#", "AppleScript"]
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Clojure", "ActionScript", "Refactor", "TrailingSpaces", "ASP", "D", "C#", "AppleScript", "Colorcoder"]
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Clojure", "ActionScript", "Refactor", "TrailingSpaces", "ASP", "D", "C#", "AppleScript"]
reloading plugin Colorcoder.colorcoder
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 127, in reload_plugin
    el.on_activated(v)
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 56, in on_activated
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 69, in on_load
TypeError: unorderable types: int() > NoneType()
reloading Packages/Colorcoder/colorcoder.sublime-settings
generating syntax summary
Traceback (most recent call last):
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 101, in update_scopes
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 106, in update_use_textcommand
AttributeError: 'NoneType' object has no attribute 'load_settings'
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 178, in maybefixscheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
error: Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
[Errno 36] File name too long: '/home/user/.config/sublime-text-3/Packages/Colorcoder/Monokai (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (SL) (Colorcoded).tmTheme'
reloading Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 178, in maybefixscheme
AttributeError: 'NoneType' object has no attribute 'load_settings'
error: Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
[Errno 36] File name too long: '/home/user/.config/sublime-text-3/Packages/Colorcoder/Monokai (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (SL) (Colorcoded).tmTheme'
Traceback (most recent call last):
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 101, in update_scopes
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 106, in update_use_textcommand
AttributeError: 'NoneType' object has no attribute 'load_settings'
error: Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
[Errno 36] File name too long: '/home/user/.config/sublime-text-3/Packages/Colorcoder/Monokai (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded) (SL) (Colorcoded).tmTheme'
reloading Packages/User/colorcoder.sublime-settings
Traceback (most recent call last):
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 101, in update_scopes
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "colorcoder in /home/user/.config/sublime-text-3/Installed Packages/Colorcoder.sublime-package", line 106, in update_use_textcommand
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

**Comment by vprimachenko** [comment]
aw yeah, it seems i managed to deadcode the check for this, thanks fro reporting

**Comment by gamicklisafisherr** [comment]
I think in your case "Long Path Tool" can help you to resolve this problem as I have seen it has been suggested by many people in the blogs.
