### ISSUE TITLE
Any time I try to use, I get this error

### ISSUE THREAD

**Issue by mklingen** [vprimachenko/Sublime-Colorcoder#53]
Installing on Sublime Text 3 in the way described in the readme, whenever I try to run the color coder plugin by switching the syntax mode, the console spits out this error:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 208, in on_load
    callback.on_load(v)
  File "/home/mklingen/.config/sublime-text-3/Packages/Colorcoder/colorcoder.py", line 69, in on_load
    if view.size() > set.get('max_size') and not view.settings().get('forcecolorcode',False):
TypeError: unorderable types: int() > NoneType()

```

And then fails to color code.

**Comment by vprimachenko** [comment]
does `Preferences`▶`Package settings`▶`Colorcoder`▶`Settings — Default` open anything similar to [this](https://github.com/vprimachenko/Sublime-Colorcoder/blob/master/colorcoder.sublime-settings)?
